# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cutlistgenerator\ui\helpdialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1127, 712)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.main)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.main, "")
        self.cut_job = QtWidgets.QWidget()
        self.cut_job.setObjectName("cut_job")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cut_job)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.cut_job)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_3.addWidget(self.textBrowser_2)
        self.tabWidget.addTab(self.cut_job, "")
        self.cut_job_search = QtWidgets.QWidget()
        self.cut_job_search.setObjectName("cut_job_search")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cut_job_search)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.cut_job_search)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_4.addWidget(self.textBrowser_3)
        self.tabWidget.addTab(self.cut_job_search, "")
        self.product = QtWidgets.QWidget()
        self.product.setObjectName("product")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.product)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.product)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_5.addWidget(self.textBrowser_4)
        self.tabWidget.addTab(self.product, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main), _translate("Dialog", "Main Window"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/HelpWindow/Images/Help/Cut_Job_Dialog.PNG\" /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cut_job), _translate("Dialog", "Cut Job"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cut_job_search), _translate("Dialog", "Cut Job Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.product), _translate("Dialog", "Product"))
import resource_rc
