# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\source\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from cutlistgenerator.customwidgets.customqtable import CustomQTableWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1194, 857)
        MainWindow.setStyleSheet(
            "/* ======================= Tab Widget ============================= */\n"
            "QTabWidget::pane { /* The tab widget frame */\n"
            "    border-top: 2px solid #C2C7CB;\n"
            "}\n"
            "\n"
            "QTabWidget::tab-bar {\n"
            "    left: 5px; /* move to the right by 5px */\n"
            "}\n"
            "\n"
            "/* Style the tab using the tab sub-control. Note that\n"
            "    it reads QTabBar _not_ QTabWidget */\n"
            "QTabBar::tab {\n"
            "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
            "                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
            "    border: 2px solid #C4C4C3;\n"
            "    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
            "    border-top-left-radius: 4px;\n"
            "    border-top-right-radius: 4px;\n"
            "    min-width: 25ex;\n"
            "    padding: 2px;\n"
            "}\n"
            "\n"
            "QTabBar::tab:selected, QTabBar::tab:hover {\n"
            "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
            "                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
            "}\n"
            "\n"
            "QTabBar::tab:selected {\n"
            "    border-color: #9B9B9B;\n"
            "    border-bottom-color: #C2C7CB; /* same as pane color */\n"
            "}\n"
            "\n"
            "QTabBar::tab:!selected {\n"
            "    margin-top: 2px; /* make non-selected tabs look smaller */\n"
            "}\n"
            "\n"
            "/* make use of negative margins for overlapping tabs */\n"
            "QTabBar::tab:selected {\n"
            "    /* expand/overlap to the left and right by 4px */\n"
            "    margin-left: -4px;\n"
            "    margin-right: -4px;\n"
            "}\n"
            "\n"
            "QTabBar::tab:first:selected {\n"
            "    margin-left: 0; /* the first selected tab has nothing to overlap with on the left */\n"
            "}\n"
            "\n"
            "QTabBar::tab:last:selected {\n"
            "    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
            "}\n"
            "\n"
            "QTabBar::tab:only-one {\n"
            "    margin: 0; /* if there is only one tab, we don't want overlapping margins */\n"
            "}\n"
            "\n"
            "/* ======================= Push Button ============================= */\n"
            "QPushButton {\n"
            "    border: 2px solid #8f8f91;\n"
            "    border-radius: 4px;\n"
            "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
            "}\n"
            "\n"
            "QPushButton:flat {\n"
            "    border: none; /* no border for a flat push button */\n"
            "    background-color: none;\n"
            "}\n"
            "\n"
            "\n"
            "/* ======================= Tool Button ============================= */\n"
            "QToolButton {\n"
            "    border: 2px solid #8f8f91;\n"
            "    border-radius: 4px;\n"
            "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
            "}\n"
            "\n"
            "QToolButton:pressed {\n"
            "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
            "}\n"
            "\n"
            "QToolButton:flat:pressed {\n"
            "    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
            "}\n"
            "\n"
            "QToolButton:flat {\n"
            "    border: none; /* no border for a flat push button */\n"
            "    background-color: none;\n"
            "}"
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.salesOrder = QtWidgets.QWidget()
        self.salesOrder.setObjectName("salesOrder")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.salesOrder)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_16 = QtWidgets.QLabel(self.salesOrder)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.soNumberSearchLineEdit = QtWidgets.QLineEdit(self.salesOrder)
        self.soNumberSearchLineEdit.setObjectName("soNumberSearchLineEdit")
        self.formLayout_4.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.soNumberSearchLineEdit
        )
        self.label_17 = QtWidgets.QLabel(self.salesOrder)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.salesOrder)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.soStatusSearchComboBox = QtWidgets.QComboBox(self.salesOrder)
        self.soStatusSearchComboBox.setObjectName("soStatusSearchComboBox")
        self.formLayout_4.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.soStatusSearchComboBox
        )
        self.customerNameSearchLineEdit = QtWidgets.QLineEdit(self.salesOrder)
        self.customerNameSearchLineEdit.setObjectName("customerNameSearchLineEdit")
        self.formLayout_4.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.customerNameSearchLineEdit
        )
        self.verticalLayout.addLayout(self.formLayout_4)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_17.addItem(spacerItem)
        self.searchPushButton = QtWidgets.QPushButton(self.salesOrder)
        self.searchPushButton.setMinimumSize(QtCore.QSize(60, 25))
        self.searchPushButton.setMaximumSize(QtCore.QSize(60, 25))
        self.searchPushButton.setObjectName("searchPushButton")
        self.horizontalLayout_17.addWidget(self.searchPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.soSearchResultTableWidget = CustomQTableWidget(self.salesOrder)
        self.soSearchResultTableWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers
        )
        self.soSearchResultTableWidget.setAlternatingRowColors(True)
        self.soSearchResultTableWidget.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection
        )
        self.soSearchResultTableWidget.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows
        )
        self.soSearchResultTableWidget.setObjectName("soSearchResultTableWidget")
        self.soSearchResultTableWidget.setColumnCount(16)
        self.soSearchResultTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.soSearchResultTableWidget.setHorizontalHeaderItem(15, item)
        self.soSearchResultTableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.soSearchResultTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.soSearchResultTableWidget.horizontalHeader().setStretchLastSection(True)
        self.soSearchResultTableWidget.verticalHeader().setVisible(False)
        self.soSearchResultTableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.soSearchResultTableWidget)
        self.tabWidget.addTab(self.salesOrder, "")
        self.cutJob = QtWidgets.QWidget()
        self.cutJob.setObjectName("cutJob")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.cutJob)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget.addTab(self.cutJob, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1194, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_16.setText(_translate("MainWindow", "Number:"))
        self.label_17.setText(_translate("MainWindow", "Customer:"))
        self.label_18.setText(_translate("MainWindow", "Status:"))
        self.soStatusSearchComboBox.setToolTip(
            _translate(
                "MainWindow",
                "<ul>\n"
                "<li><b>Inventory</b> - Can be purchased and sold and stocked in inventory.</li>\n"
                "<li><b>Service</b> - Can be purchased and sold but is not stocked in inventory.</li>\n"
                "<li><b>Labor</b> - Cannot be purchased or sold, but can be added during manufacturing or reconciling.</li>\n"
                "<li><b>Overhead</b> - Can be included as a component of a part's cost during manufacturing.</li>\n"
                "<li><b>Non-Inventory</b> - Can be purchased and sold but is not tracked in inventory.</li>\n"
                "<li><b>Internal Use</b> - Can be purchased but is not sold or stocked in inventory.</li>\n"
                "<li><b>Capital Equipment</b> - Equipment that depreciates in value and can be purchased but is not sold or stocked in inventory.</li>\n"
                "<li><b>Shipping</b> - Can be purchased or sold, but is not stocked in inventory.</li>\n"
                "</ul>",
            )
        )
        self.searchPushButton.setText(_translate("MainWindow", "Search"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Number"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer Name"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date Issued"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fulfillment Date"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Customer PO"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Line"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Part Number"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Description"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Qty Ordered"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Qty Left To Ship"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "UOM"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Type"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Status"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Date Fulfilled"))
        item = self.soSearchResultTableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Date Scheduled"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.salesOrder),
            _translate("MainWindow", "Sales Order"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.cutJob), _translate("MainWindow", "Cut Job")
        )
