# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cutlistgenerator\ui\wirecuttersearchdialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wire_cutter_search_dialog(object):
    def setupUi(self, wire_cutter_search_dialog):
        wire_cutter_search_dialog.setObjectName("wire_cutter_search_dialog")
        wire_cutter_search_dialog.resize(591, 386)
        self.verticalLayout = QtWidgets.QVBoxLayout(wire_cutter_search_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(wire_cutter_search_dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name_line_edit = QtWidgets.QLineEdit(wire_cutter_search_dialog)
        self.name_line_edit.setObjectName("name_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_line_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.search_push_button = QtWidgets.QPushButton(wire_cutter_search_dialog)
        self.search_push_button.setObjectName("search_push_button")
        self.verticalLayout.addWidget(self.search_push_button)
        self.wire_cutter_table_widget = QtWidgets.QTableWidget(wire_cutter_search_dialog)
        self.wire_cutter_table_widget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.wire_cutter_table_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.wire_cutter_table_widget.setObjectName("wire_cutter_table_widget")
        self.wire_cutter_table_widget.setColumnCount(5)
        self.wire_cutter_table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.wire_cutter_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.wire_cutter_table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.wire_cutter_table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.wire_cutter_table_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.wire_cutter_table_widget.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.wire_cutter_table_widget)
        self.select_push_button = QtWidgets.QPushButton(wire_cutter_search_dialog)
        self.select_push_button.setObjectName("select_push_button")
        self.verticalLayout.addWidget(self.select_push_button)

        self.retranslateUi(wire_cutter_search_dialog)
        QtCore.QMetaObject.connectSlotsByName(wire_cutter_search_dialog)

    def retranslateUi(self, wire_cutter_search_dialog):
        _translate = QtCore.QCoreApplication.translate
        wire_cutter_search_dialog.setWindowTitle(_translate("wire_cutter_search_dialog", "Wire Cutter Search"))
        self.label.setText(_translate("wire_cutter_search_dialog", "Name:"))
        self.search_push_button.setToolTip(_translate("wire_cutter_search_dialog", "Search for cut jobs matching fields above."))
        self.search_push_button.setText(_translate("wire_cutter_search_dialog", "Search"))
        self.wire_cutter_table_widget.setSortingEnabled(False)
        item = self.wire_cutter_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("wire_cutter_search_dialog", "Id"))
        item = self.wire_cutter_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("wire_cutter_search_dialog", "Name"))
        item = self.wire_cutter_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("wire_cutter_search_dialog", "Max Wire Size"))
        item = self.wire_cutter_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("wire_cutter_search_dialog", "Processing Speed (ft/min)"))
        item = self.wire_cutter_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("wire_cutter_search_dialog", "Details"))
        self.select_push_button.setToolTip(_translate("wire_cutter_search_dialog", "Opens the selected cut job."))
        self.select_push_button.setText(_translate("wire_cutter_search_dialog", "Select"))
