# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './cutlistgenerator/ui/wirecutterdialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wire_cutter_dialog(object):
    def setupUi(self, wire_cutter_dialog):
        wire_cutter_dialog.setObjectName("wire_cutter_dialog")
        wire_cutter_dialog.resize(517, 320)
        wire_cutter_dialog.setMinimumSize(QtCore.QSize(517, 320))
        wire_cutter_dialog.setMaximumSize(QtCore.QSize(517, 320))
        self.verticalLayout = QtWidgets.QVBoxLayout(wire_cutter_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(wire_cutter_dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name_line_edit = QtWidgets.QLineEdit(wire_cutter_dialog)
        self.name_line_edit.setObjectName("name_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_line_edit)
        self.label_3 = QtWidgets.QLabel(wire_cutter_dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.max_wire_size_spin_box = QtWidgets.QSpinBox(wire_cutter_dialog)
        self.max_wire_size_spin_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_wire_size_spin_box.setMaximum(10000)
        self.max_wire_size_spin_box.setObjectName("max_wire_size_spin_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.max_wire_size_spin_box)
        self.label_4 = QtWidgets.QLabel(wire_cutter_dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.processing_speed_double_spin_box = QtWidgets.QDoubleSpinBox(wire_cutter_dialog)
        self.processing_speed_double_spin_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.processing_speed_double_spin_box.setMaximum(10000.0)
        self.processing_speed_double_spin_box.setSingleStep(0.5)
        self.processing_speed_double_spin_box.setProperty("value", 150.0)
        self.processing_speed_double_spin_box.setObjectName("processing_speed_double_spin_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.processing_speed_double_spin_box)
        self.label_2 = QtWidgets.QLabel(wire_cutter_dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.details_text_edit = QtWidgets.QTextEdit(wire_cutter_dialog)
        self.details_text_edit.setObjectName("details_text_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.details_text_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.save_push_button = QtWidgets.QPushButton(wire_cutter_dialog)
        self.save_push_button.setObjectName("save_push_button")
        self.verticalLayout.addWidget(self.save_push_button)

        self.retranslateUi(wire_cutter_dialog)
        QtCore.QMetaObject.connectSlotsByName(wire_cutter_dialog)

    def retranslateUi(self, wire_cutter_dialog):
        _translate = QtCore.QCoreApplication.translate
        wire_cutter_dialog.setWindowTitle(_translate("wire_cutter_dialog", "Wire Cutter"))
        self.label.setText(_translate("wire_cutter_dialog", "Name:"))
        self.name_line_edit.setToolTip(_translate("wire_cutter_dialog", "Unique name for this wire cutter."))
        self.label_3.setText(_translate("wire_cutter_dialog", "Max Wire Size:"))
        self.max_wire_size_spin_box.setToolTip(_translate("wire_cutter_dialog", "The maximum wire AWG this cutter can process."))
        self.max_wire_size_spin_box.setSuffix(_translate("wire_cutter_dialog", " AWG"))
        self.label_4.setText(_translate("wire_cutter_dialog", "Processing Speed:"))
        self.processing_speed_double_spin_box.setToolTip(_translate("wire_cutter_dialog", "Average processing speed for this cutter."))
        self.processing_speed_double_spin_box.setSuffix(_translate("wire_cutter_dialog", " ft/min"))
        self.label_2.setText(_translate("wire_cutter_dialog", "Details:"))
        self.details_text_edit.setToolTip(_translate("wire_cutter_dialog", "Any other info."))
        self.save_push_button.setToolTip(_translate("wire_cutter_dialog", "Save this wire cutter."))
        self.save_push_button.setText(_translate("wire_cutter_dialog", "Save"))
