CREATE TABLE `fishbowlsodata` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `soNum` varchar(255) NOT NULL,
  `customerName` varchar(255) NOT NULL,
  `dueDate` datetime(6) NOT NULL,
  `soLineItem` int(11) NOT NULL,
  `productNum` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `qtyToFulfill` decimal(28,9) NOT NULL,
  `qtyLeftToShip` decimal(28,9) NOT NULL,
  `uom` varchar(15) NOT NULL,
  `itemAddedToCutList` bit(1) DEFAULT 0,
  `assignedCutter` varchar(255) DEFAULT NULL,
  `qtyCut` decimal(28,9) DEFAULT NULL,
  `itemCut` bit(1) GENERATED ALWAYS AS (CASE WHEN `dateCutEnd` THEN 1 ELSE 0 END),
  `dateCutStart` datetime(6) DEFAULT NULL,
  `dateCutEnd` datetime(6) DEFAULT NULL,
  `itemTerminated` bit(1) GENERATED ALWAYS AS (CASE WHEN `dateTerminationEnd` THEN 1 ELSE 0 END),
  `dateTerminationStart` datetime(6) DEFAULT NULL,
  `dateTerminationEnd` datetime(6) DEFAULT NULL,
  `itemSpliced` bit(1) GENERATED ALWAYS AS (CASE WHEN `dateSpliceEnd` THEN 1 ELSE 0 END),
  `dateSpliceStart` datetime(6) DEFAULT NULL,
  `dateSpliceEnd` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;